### ISSUE TITLE
Final N@TM Project Plan 

### ISSUE THREAD

**Issue by Deeskili** [AdiBricks/Tri3CombinedFrontend#1]
New feature - Grocery store item sorter 

- [ ] Create backend with database to store different items of different categories (desserts, meats, dairy, non-consumable) 
- [ ] Create frontend that pulls from backend and displays a unique item block for each item 
- [ ] Should include sorting/searching algorithm 
- [ ] Create algorithm to be able to sort items based on their category 
- [ ] Deploy backend ASAP after base functionality created
